sudo: required
services:
    - docker
before_install:
    - docker build -t shklnrj/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true shklnrj/react-test yarn test --watchAll=false --coverage

after_success:
    - docker build -t shklnrj/multi-client ./client
    - docker build -t shklnrj/multi-nginx ./nginx
    - docker build -t shklnrj/multi-server ./server
    - docker build -t shklnrj/multi-worker ./worker
    # login into the docker hub using the credentials
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take the images and push the images to docker hub
    - docker push shklnrj/multi-client
    - docker push shklnrj/multi-nginx
    - docker push shklnrj/multi-server
    - docker push shklnrj/multi-worker
deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket-name: elasticbeanstalk-us-east-1-375263320264
    bucket-path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

