sudo: required
services:
    - docker
before_install:
    - docker build -t shklnrj/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true shklnrj/react-test yarn test --watchAll=false --coverage

after_success:
    - docker build -t shklnrj/multi-client ./client
    - docker build -t shklnrj/multi-nginx ./nginx
    - docker build -t shklnrj/multi-server ./server
    - docker build -t shklnrj/multi-worker ./worker
    # login into the docker hub using the credentials
    